### ISSUE TITLE
Create the contributing guidelines

### ISSUE THREAD

**Issue by CatherineKiiru** [chaoss/GitHub-Copilot-Hackathon-Project#1]
The contributing guidelines should describe how to contribute to the project, how to write commits and how to create a PR. 

Include the following details in the contributing.md file:

1. How to run the project in a local environment
2. List the tools required to run the project locally
3. Describe how to install packages
4. Describe how to create a new branch
5. Describe how to run local host
6. Describe how to commit changes and how to push them to GitHub

Here's a sample you can use for reference [contributing guidelines](https://github.com/badging/badging/blob/main/CONTRIBUTING.md )

**Comment by Kudzmat** [comment]
Thanks, Catherine - I'm thinking that I can work on 1-3, and then Faith could do 4-6? 

Other than GitHub Copilot itself, are there any other specific tools/packages required for running the project that I should know of or mention? Just want to make sure we're all on the same page and I don't go off doing my own thing!

**Comment by CatherineKiiru** [comment]
Hi @Kudzmat, yes you can work on the areas you prefer. Collaborate with Faith so that the guidelines are cohesive. The tools we'll use for the project are:

- Frontend Library - ReactJS
- CSS Framework - Tailwind CSS
- Bundler/Build Tool - Vite
- Test Runner - Vitest
- Routing Implementation - React Router
- Component Library - Flowbite
- Icon Pack - Material Symbols by Google

**Comment by FaithKovi** [comment]
@Kudzmat, we can collaborate on slack
