### ISSUE TITLE
Create the footer section

### ISSUE THREAD

**Issue by CatherineKiiru** [chaoss/GitHub-Copilot-Hackathon-Project#10]
### Description
Implement the footer section as per the design. Also implement the mobile responsive design. Try to ensure the component is pixel perfect.

![Screenshot from 2023-07-18 20-27-31](https://github.com/chaoss/GitHub-Copilot-Hackathon-Project/assets/66266208/f9d6ee82-9de3-4cae-9c14-0139e6523b84)

### Scenarios
- A user needs to view the footer section as per the design
- A user can view the desktop and mobile version
- Add hover effects to the links 

### Tasks

- [ ]  Implement the section as per the design
- [ ] Use GitHub CoPilot for the project to generate code suggestions
- [ ]  Submit PR as per the contributing guidelines

**Comment by adeyinkaoresanya** [comment]
Hi @CatherineKiiru I would like to work on this. Kindly assign to me

**Comment by CatherineKiiru** [comment]
Hi @adeyinkaoresanya I have assigned. Have you managed to work with CoPilot?

**Comment by CatherineKiiru** [comment]
Hi @adeyinkaoresanya let me know how much time you'll need to complete this issue.

**Comment by CatherineKiiru** [comment]
Hi @Shubhankar-1 can you manage to work on this issue?

**Comment by Shubhankar-1** [comment]
Sure

**Comment by CatherineKiiru** [comment]
Hi @Shubhankar-1 for the social links, add links to CHAOSS Africa's relevant social media platforms.
