### ISSUE TITLE
Fix contributing.md link in README.md

### ISSUE THREAD

**Issue by FaithKovi** [chaoss/GitHub-Copilot-Hackathon-Project#15]
The link to contributing.md in the readme needs to be changed.

**Comment by FaithKovi** [comment]
@CatherineKiiru I will love to fix this

**Comment by CatherineKiiru** [comment]
Hi @FaithKovi proceed. Also fix this section, the slack-bot link might be misleading:

![Screenshot from 2023-07-21 14-25-54](https://github.com/chaoss/GitHub-Copilot-Hackathon-Project/assets/66266208/07762d86-3f01-4c77-b62e-f675d15db3eb)

**Comment by FaithKovi** [comment]
Okay sure I will @CatherineKiiru

**Comment by FaithKovi** [comment]
@CatherineKiiru the issue has been fixed and a PR created
