### ISSUE TITLE
Hacktoberfest guidelines

### ISSUE THREAD

**Issue by CatherineKiiru** [chaoss/GitHub-Copilot-Hackathon-Project#31]
## Hacktoberfest Guidelines
- Create the guidelines for contributing to this project, during Hactoberfest. For code contributions you can add a link to the contributing readme file
- Include guidelines for designers i.e the figma file link, contact person for design issues and how to contribute to design issues.

## Hacktoberfest issues
Create good first issues for hacktoberfest. Contributors will contribute to both design and code issues

**Comment by EdiRomao** [comment]
qual é a linguagem a ser usada?

**Comment by peculiaruc** [comment]
Hi @CatherineKiiru is this issue still open?

**Comment by CatherineKiiru** [comment]
Hi @peculiaruc yes it is, I have assigned it to you. Create a Hactoberfest Read me for the guidelines, similar to the contributing Readme file.

**Comment by Ajiboso-Adeola** [comment]
Hi @CatherineKiiru , I would like to work on this issue

**Comment by peculiaruc** [comment]
> Hi @peculiaruc yes it is, I have assigned it to you. Create a Hactoberfest Read me for the guidelines, similar to the contributing Readme file. 

I am on it @peculiaruc
