### ISSUE TITLE
About us Page Design Afos Project.

### ISSUE THREAD

**Issue by iamkingsleey** [chaoss/GitHub-Copilot-Hackathon-Project#32]
We need a design of the About Us page highlighting in detail the goals and objectives of the Afos Project. The PRD and style guide will be made accessible to potential contributors to guide your design process.

**Comment by Petsamuel** [comment]
I'd like to work on this

**Comment by lizzlix** [comment]
I'm interested in this. 
@iamkingsleey how do i get the resources to get started?

**Comment by iamkingsleey** [comment]
Thank you @lizzlix for your interest in working on this issue. I'd like to clarify a few things as we enter Hacktoberfest season and welcome new contributors. Here are some guidelines for contributing:

Please join our Slack community channel for better communication: [Link to join](https://join.slack.com/t/chaoss-workspace/shared_invite/zt-2541kvhn5-Dhe~n0PjxBMpIfUtkRVSCw)

It's essential to note that this is an open issue, which means multiple contributors may be assigned to these tasks.

We usually have a design call every Wednesday 11am - Noon WAT biweekly where we talk about the tasks. You can provide your email address to be added to the call.

We will provide you with access to our Afos Assets, allowing you to start working on this project.

**Comment by lizzlix** [comment]
> Thank you @lizzlix for your interest in working on this issue. I'd like to clarify a few things as we enter Hacktoberfest season and welcome new contributors. Here are some guidelines for contributing:
> 
> Please join our Slack community channel for better communication: [Link to join](https://join.slack.com/t/chaoss-workspace/shared_invite/zt-2541kvhn5-Dhe~n0PjxBMpIfUtkRVSCw)
> 
> It's essential to note that this is an open issue, which means multiple contributors may be assigned to these tasks.
> 
> We usually have a design call every Wednesday 11am - Noon WAT biweekly where we talk about the tasks. You can provide your email address to be added to the call.
> 
> We will provide you with access to our Afos Assets, allowing you to start working on this project.

Alright. My email is; Israelphelisvibe@gmail.com

**Comment by A-Timi** [comment]
Hi @iamkingsleey, I'm interested in working on the About us page
