### ISSUE TITLE
Afos Project Page Design

### ISSUE THREAD

**Issue by iamkingsleey** [chaoss/GitHub-Copilot-Hackathon-Project#33]
This page is divided into two:

1. **View All Page:** 
This page allows users to view all the projects listed on Afos. The design should accommodate a large number of projects by incorporating pagination. Users should also have the ability to search and filter projects by category on the "View All" page.

2. **Project Details Page:** 
This page allows users to access specific project details listed on the project page. The design should consider the data provided during project submission.

**Comment by ghost** [comment]
hey there ! is anyone working on this issue ? I would like to try

**Comment by CatherineKiiru** [comment]
Hi @capedCrusaderr I have assigned you the issue

**Comment by ghost** [comment]
hi @CatherineKiiru , thank for assigning me the project . It would be great that you could guide me regarding the issue. A guideline would be a great start for me.
😃

**Comment by ghost** [comment]
I am  a bit confused since I checked a Figma file in readme , do I have to remake the page ?

**Comment by iamkingsleey** [comment]
Thank you @capedCrusaderr  for your interest in working on this issue. I'd like to clarify a few things as we enter Hacktoberfest season and welcome new contributors. Here are some guidelines for contributing:

Please join our Slack community channel for better communication: [Link to join](https://join.slack.com/t/chaoss-workspace/shared_invite/zt-2541kvhn5-Dhe~n0PjxBMpIfUtkRVSCw)

It's essential to note that this is an open issue, which means multiple contributors may be assigned to these tasks.

We usually have a design call every Wednesday 11am - Noon WAT biweekly where we talk about the tasks. You can provide your email address to be added to the call. 

We will provide you with access to our Afos Assets, allowing you to start working on this project.
