### ISSUE TITLE
Project Submission Page

### ISSUE THREAD

**Issue by iamkingsleey** [chaoss/GitHub-Copilot-Hackathon-Project#34]
This page allows users to submit the required information needed to have their projects featured on Afos. The submitted information will be manually reviewed by an admin who will then approve its display on the website.

**Comment by KaptainCS3** [comment]
@iamkingsleey please assign me

**Comment by A33sha** [comment]
Hi can i take on this design

**Comment by CatherineKiiru** [comment]
Hi @A33sha I have assigned you the issue, @iamkingsleey will guide you

**Comment by A33sha** [comment]
Thank you @CatherineKiiru. @iamkingsleey how can I reach out to you please

**Comment by iamkingsleey** [comment]
Thank you @A33sha for your interest in working on this issue. I'd like to clarify a few things as we enter Hacktoberfest season and welcome new contributors. Here are some guidelines for contributing:

Please join our Slack community channel for better communication: [Link to join](https://join.slack.com/t/chaoss-workspace/shared_invite/zt-2541kvhn5-Dhe~n0PjxBMpIfUtkRVSCw)

It's essential to note that this is an open issue, which means multiple contributors may be assigned to these tasks.

We usually have a design call every Wednesday 11am - Noon WAT biweekly where we talk about the tasks. You can provide your email address to be added to the call.

We will provide you with access to our Afos Assets, allowing you to start working on this project.
