### ISSUE TITLE
 Admin Dashboard Design

### ISSUE THREAD

**Issue by iamkingsleey** [chaoss/GitHub-Copilot-Hackathon-Project#35]
A minimal admin dashboard that enables Afos Admin to review and approve submitted projects.

**Comment by Abishkardhenga** [comment]
hey iamkingsleey , can i get the design ??

**Comment by CatherineKiiru** [comment]
Hi @Aabiskar-dhenga I will assign you the issue. @iamkingsleey could you guide the designers on how to get started?

**Comment by iamkingsleey** [comment]
Thank you @Aabiskar-dhenga for your interest in working on this issue. I'd like to clarify a few things as we enter Hacktoberfest season and welcome new contributors. Here are some guidelines for contributing:

Please join our Slack community channel for better communication: [Link to join](https://join.slack.com/t/chaoss-workspace/shared_invite/zt-2541kvhn5-Dhe~n0PjxBMpIfUtkRVSCw)

It's essential to note that this is an open issue, which means multiple contributors may be assigned to these tasks.

We usually have a design call every Wednesday 11am - Noon WAT biweekly where we talk about the tasks. You can provide your email address to be added to the call. 

We will provide you with access to our Afos Assets, allowing you to start working on this project.

**Comment by Ladyruth** [comment]
Hi,  @CatherineKiiru I'd like to work on this too.

**Comment by Abishkardhenga** [comment]
> Thank you @Aabiskar-dhenga for your interest in working on this issue. I'd like to clarify a few things as we enter Hacktoberfest season and welcome new contributors. Here are some guidelines for contributing:
> 
> Please join our Slack community channel for better communication: [Link to join](https://join.slack.com/t/chaoss-workspace/shared_invite/zt-2541kvhn5-Dhe~n0PjxBMpIfUtkRVSCw)
> 
> It's essential to note that this is an open issue, which means multiple contributors may be assigned to these tasks.
> 
> We usually have a design call every Wednesday 11am - Noon WAT biweekly where we talk about the tasks. You can provide your email address to be added to the call.
> 
> We will provide you with access to our Afos Assets, allowing you to start working on this project.

Thanks  for response I have meessage  on slack  group . Hope You response soon .

**Comment by CatherineKiiru** [comment]
Hi @iamkingsleey have the designs for these issues been completed?

**Comment by Zurumm** [comment]
Hey, please is this still open to be worked on?

**Comment by CatherineKiiru** [comment]
Hi @iamkingsleey are the designs still being worked on? If not, I'd like to close the 

> Hey, please is this still open to be worked on?

Hi @Zurumm the project is on hold. When we open it up again we'll raise new issues.
