### ISSUE TITLE
Create the projects section

### ISSUE THREAD

**Issue by CatherineKiiru** [chaoss/GitHub-Copilot-Hackathon-Project#5]
### Description
Implement the projects section as per the design. Also implement the mobile responsive design. Try to ensure the component is pixel perfect.

![Screenshot from 2023-07-18 19-18-00](https://github.com/chaoss/GitHub-Copilot-Hackathon-Project/assets/66266208/53c0a3a1-9a03-4f7a-85ed-1aec0aa6ef1a)

### Scenarios
- A user needs to view the project section as per the design
- A user can view the desktop and mobile version
- Try to add hover effects to the buttons

### Tasks
- [ ] Implement the section as per the design
- [ ]  Use GitHub CoPilot for the project to generate code suggestions
- [ ] Submit PR as per the contributing guidelines

**Comment by TemitopeAsama** [comment]
Hi @CatherineKiiru I'd like to take this on. Thank you!

**Comment by TemitopeAsama** [comment]
@CatherineKiiru

**Comment by CatherineKiiru** [comment]
Hi @TemitopeAsama I have assigned the issue to you. How long do you feel it would take you to complete the section?

**Comment by TemitopeAsama** [comment]
Hello. Sorry about my late reply. I didn't get a notification for this. What is the speculated timeline? I have a tight work schedule, so I'd say two weeks at least.

**Comment by CatherineKiiru** [comment]
Hi @TemitopeAsama can you make some commits within this week? We still need your feedback on CoPilot, try to work on the project within this week

**Comment by CatherineKiiru** [comment]
Hi @TemitopeAsama how's this issue coming along? Are you done with this section?

**Comment by CatherineKiiru** [comment]
Hi @TemitopeAsama please confirm how far you are with the issue. I'd like to assign it to someone else if you're not in a position to complete it within this week.

**Comment by CatherineKiiru** [comment]
Hi @TemitopeAsama I have reassigned this issue to @Shubhankar-1

**Comment by Shubhankar-1** [comment]
Hi @CatherineKiiru , shouldn't the card colors be distinct from the background color?

**Comment by CatherineKiiru** [comment]
@Shubhankar-1 the current design uses a green border to distinguish the background from the cards. I'll relay this feedback to the design team, in the mean time, you can work with the design.

**Comment by Shubhankar-1** [comment]
@CatherineKiiru  okay I have completed work should I create pull request or wait for design team feedback ?

**Comment by CatherineKiiru** [comment]
Hi @CatherineKiiru create the PR. We'll review the designs after this project. I'm assigning you another one.

**Comment by CatherineKiiru** [comment]
@Shubhankar-1 add hover effects on the buttons

**Comment by CatherineKiiru** [comment]
Hi @Shubhankar-1 I'm reopening this issue because we've made some updates to the project section. Let me know if you're available to work on the changes. See the new design here https://www.figma.com/file/mALWb4e0vqfBbtRwop3g16/Afos?type=design&node-id=44-930&mode=design&t=ho2NpaHGhEa8ZnEM-0 


You'll need to add links to the "view project" buttons. You can find links for each project here https://docs.google.com/document/d/1vHBmJO1GpcrgpvkKjOrIvUOehmp7z12ujJMXpjSnroE/edit

**Comment by Shubhankar-1** [comment]
Okay
