### ISSUE TITLE
Create the empowerment section

### ISSUE THREAD

**Issue by CatherineKiiru** [chaoss/GitHub-Copilot-Hackathon-Project#6]
### Description
Implement the empowerment section as per the design. Also implement the mobile responsive design. Try to ensure the component is pixel perfect.

![Screenshot from 2023-07-18 19-33-06](https://github.com/chaoss/GitHub-Copilot-Hackathon-Project/assets/66266208/ca3dece4-a861-4b21-8aeb-56ecd96a4c2f)

### Scenarios
A user needs to view the empowerment section as per the design
A user can view the desktop and mobile version

Tasks
- [ ] Implement the section as per the design
- [ ] Use GitHub CoPilot for the project to generate code suggestions
- [ ] Implement hover states on the button element
- [ ] Submit PR as per the contributing guidelines

**Comment by Shubhankar-1** [comment]
Hey @CatherineKiiru can I work on this issue as well ?

**Comment by CatherineKiiru** [comment]
Hi @Shubhankar-1 I have assigned you the issue. Remember to still use Copilot for this section
