### ISSUE TITLE
Create the collaboration section

### ISSUE THREAD

**Issue by CatherineKiiru** [chaoss/GitHub-Copilot-Hackathon-Project#7]
### Description
Implement the collaboration section as per the design. Also implement the mobile responsive design. Try to ensure the component is pixel perfect.

![Screenshot from 2023-07-18 19-38-37](https://github.com/chaoss/GitHub-Copilot-Hackathon-Project/assets/66266208/83871573-ccb0-4f42-8f20-69e0b04b17f6)

### Scenarios
- A user needs to view the collaboration section as per the design
- A user can view the desktop and mobile version

### Tasks
- [ ] Implement the section as per the design
- [ ] Use GitHub CoPilot for the project to generate code suggestions
- [ ] Submit PR as per the contributing guidelines

**Comment by bhantsi** [comment]
I would like to work on this please assign it to me

**Comment by CatherineKiiru** [comment]
@bhantsi I'll assign it to you. Share your email or GitHub username so we can give you a Copilot license.

**Comment by bhantsi** [comment]
> @bhantsi I'll assign it to you. Share your email or GitHub username so we can give you a Copilot license.
bhantsi@gmail.com Also I will like to have access to the Figma design

**Comment by CatherineKiiru** [comment]
Hi @bhantsi, here's the design https://www.figma.com/file/mALWb4e0vqfBbtRwop3g16/Afos?type=design&node-id=44-930&mode=design&t=pELTbqk0rRgeCA7d-0

**Comment by bhantsi** [comment]
> Hi @bhantsi, here's the design https://www.figma.com/file/mALWb4e0vqfBbtRwop3g16/Afos?type=design&node-id=44-930&mode=design&t=pELTbqk0rRgeCA7d-0
I got this 
![Screenshot from 2023-07-30 16-43-03](https://github.com/chaoss/GitHub-Copilot-Hackathon-Project/assets/26586086/92f03de8-04cb-43c0-9993-855f804f27dc)

**Comment by CatherineKiiru** [comment]
Hi @bhantsi, could you check again if you have access?

**Comment by bhantsi** [comment]
Nope, not yet approved

**Comment by CatherineKiiru** [comment]
I'll notify you once the designers give access

**Comment by bhantsi** [comment]
Ok thanks

**Comment by bhantsi** [comment]
Hi @CatherineKiiru I got the access

**Comment by CatherineKiiru** [comment]
Hi @bhantsi Proceed. Do you have access to GitHub CoPilot? You'll need to work with CoPilot so we can gather accurate feedback for the project

**Comment by bhantsi** [comment]
No I don't

**Comment by CatherineKiiru** [comment]
Ok, I'll let you know once we give you access

**Comment by CatherineKiiru** [comment]
Hi @bhantsi you now have access to CoPilot. Accept the invitation and install the CoPilot extension in your code editor.

**Comment by CatherineKiiru** [comment]
Hello @bhantsi What's the status for this issue?

**Comment by CatherineKiiru** [comment]
Hi @bhantsi, please confirm if you're still working on this issue and when you'll complete it?

**Comment by bhantsi** [comment]
Hi @CatherineKiiru yes I am working on it

**Comment by CatherineKiiru** [comment]
Hi @bhantsi, have you completed this section?

**Comment by bhantsi** [comment]
> Hi @bhantsi, have you completed this section?

Sorry, I am down with a fever. Now getting much better I will send my PR later today

**Comment by CatherineKiiru** [comment]
Hi @bhantsi I hope you're feeling better now. Have you completed this section? This is the only issue remaining and we need to close this project this coming week. Please confirm if you're still able to complete it.

**Comment by CatherineKiiru** [comment]
Hi @bhantsi are you located in Lagos? We'd like to do a video recording of your experience in using GitHub Copilot for this project. Let me know If you'd be interested in doing the recording.

**Comment by bhantsi** [comment]
Hi @CatherineKiiru, I'm definitely interested in doing the video recording. The only thing is, I live in Kano, Nigeria, which is quite a distance from Lagos. I'm not sure if there's a way to make it work considering the distance. Let's discuss and see if there's a possibility. 
Thanks!

**Comment by CatherineKiiru** [comment]
Hi @bhantsi, I've seen it's quite a long distance. We wanted to record the video with our own videographer so It might not be possible to do it considering the logistics.

**Comment by bhantsi** [comment]
Alright then, I am sorry for any inconveniences this may cause
