### ISSUE TITLE
Create the enhancement section 

### ISSUE THREAD

**Issue by CatherineKiiru** [chaoss/GitHub-Copilot-Hackathon-Project#8]
### Description
Implement the enhancement section as per the design. Also implement the mobile responsive design. Try to implement hover states and ensure the component is pixel perfect.

![Screenshot from 2023-07-18 20-16-30](https://github.com/chaoss/GitHub-Copilot-Hackathon-Project/assets/66266208/a92f47d9-38c3-4978-8506-f4e7208b826a) 

### Scenarios
- A user needs to view the enhancement section as per the design
- A user can view the desktop and mobile version
- Add hover effects to the buttons

### Tasks
- [ ]  Implement the section as per the design
- [ ] Use GitHub CoPilot for the project to generate code suggestions
- [ ] Submit PR as per the contributing guidelines

**Comment by Shubhankar-1** [comment]
Hello @CatherineKiiru  I'd like to work on this.

**Comment by CatherineKiiru** [comment]
Hi @Shubhankar-1 I'll assign you. Share your email address or GitHub username so I can create a free GitHub Copilot license for you.

**Comment by Shubhankar-1** [comment]
> Hi @Shubhankar-1 I'll assign you. Share your email address or GitHub username so I can create a free GitHub Copilot license for you. 

Shubhankar.nautiyal21@gmail.com

**Comment by Shubhankar-1** [comment]
@CatherineKiiru Could you please guide me on where I can get assets from?
